function(infrascal_install)
  install(TARGETS ${ARGN}
    EXPORT ${TARGET_NAME}Targets
    RUNTIME DESTINATION ${INFRASCAL_RUNTIME_INSTALL_PATH}
    LIBRARY DESTINATION ${INFRASCAL_LIBRARY_INSTALL_PATH}
    ARCHIVE DESTINATION ${INFRASCAL_ARCHIVE_INSTALL_PATH}
    INCLUDES DESTINATION ${INFRASCAL_INCLUDE_INSTALL_PATH}
  )
endfunction(infrascal_install)
